const myarr=[0,1,2,3,4,5]
const myarr2=new Array(1,2,3,4,5)
//array methods
myarr.push(6)
// console.log(myarr)
myarr.pop()
// console.log(myarr)
// myarr.unshift(9)
// console.log(myarr)
// myarr.shift()
// console.log(myarr)
// console.log(myarr.indexOf(9))
// const newarr=myarr2.join()
// console.log(newarr)
// console.log(typeof(myarr2.join()))
console.log("A",myarr)
const myn1=myarr.slice(1,3)
console.log(myn1)
console.log("B",myarr)
const myn2=myarr.splice(1,3)
console.log(myn2)
console.log("C",myarr)
